language: ruby
cache: bundler
rvm:
  - 2.7
  - 3.0
  - 3.1
  - 3.2
script:
  - bundle install --path vendor/bundle
  - bundle exec rspec
  - gem build siteimprove_api_client.gemspec
  - gem install ./siteimprove_api_client-1.0.0.gem
